// <auto-generated />
using System;
using Infraestructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Caregory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Caregory", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Electrodomésticos"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Tecnología y Electrónica"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Moda y Accesorios"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Hogar y Decoración"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Salud y Belleza"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Deportes y Ocio"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Juguetes y Juegos"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Alimentos y Bebidas"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Libros y Material Educativo"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "Jardinería y Bricolaje"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(38,17)");

                    b.HasKey("ProductId");

                    b.HasIndex("Category");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("cf324d5d-97b5-4471-ac42-a8b32abadf56"),
                            Category = 1,
                            Description = "La heladera cíclica Drean cuenta con un diseño clásico tipo Top Mount, es decir que ubica el freezer en la parte superior y en la parte inferior el refrigerador…",
                            Discount = 28,
                            ImageUrl = "https://i.imgur.com/R8YiUCy.jpeg",
                            Name = "Heladera Cíclica Drean 277Lts",
                            Price = 815.799m
                        },
                        new
                        {
                            ProductId = new Guid("15850893-6c85-4f35-85dc-f6fa16252877"),
                            Category = 1,
                            Description = "La heladera Sigma combina su cómodo diseño con una gran utilidad. En su interior, cuenta con un bandejón con tapa y 3 prácticos estantes para que puedas acomodar tus alimentos de la mejor forma…",
                            Discount = 0,
                            ImageUrl = "https://i.imgur.com/GkJkcHz.jpg",
                            Name = "Heladera Cíclica Sigma 239Lts",
                            Price = 559.999m
                        },
                        new
                        {
                            ProductId = new Guid("f813177c-0361-4ddb-b90a-3a1e9227d1c5"),
                            Category = 1,
                            Description = "La Escorial Candor S2 es una cocina de diseño clásico en color negro que cuenta con cuatro hornallas; horno y cajón parrilla independiente…",
                            Discount = 9,
                            ImageUrl = "https://i.imgur.com/Enf28Zo.jpg",
                            Name = "Cocina Escorial Candor S2 Gas Natural",
                            Price = 273.099m
                        },
                        new
                        {
                            ProductId = new Guid("f82fa483-4240-4c01-8b3a-d52f8799af0e"),
                            Category = 1,
                            Description = "La cocina electrolux 56DXQ cuenta con 2 hornos independientes, uno eléctrico y uno a gas, permitiendo que se puedan realizar preparaciones simultáneamente y con excelente calidad…",
                            Discount = 10,
                            ImageUrl = "https://i.imgur.com/UiRaVyJ.jpg",
                            Name = "Cocina Electrolux 56DXQ ",
                            Price = 999.999m
                        },
                        new
                        {
                            ProductId = new Guid("9d4f1438-edb6-4516-9ab6-694e4aa34528"),
                            Category = 2,
                            Description = "Mediante su entrada PC In podrás conectar tu PC o Notebook. Además, también ofrece la posibilidad de conectarse a través de HDMI. El LED no tiene sistema de audio incorporado… ",
                            Discount = 0,
                            ImageUrl = "https://i.imgur.com/eHBufmj.jpg",
                            Name = "Monitor Gamer Samsung 27”",
                            Price = 299.999m
                        },
                        new
                        {
                            ProductId = new Guid("646a8a2e-70d1-41a8-83ae-69ae067652e7"),
                            Category = 2,
                            Description = "Cuenta con una excelente pantalla de 27” pulgadas y resolución FHD (1920x1080) para que disfrutes de ver todo tu contenido en gran calidad.",
                            Discount = 15,
                            ImageUrl = "https://i.imgur.com/z4xwwrR.jpg",
                            Name = "Monitor Noblex 27” FHD",
                            Price = 329.999m
                        },
                        new
                        {
                            ProductId = new Guid("f4bcbc98-3a58-4a9f-9258-b67e56cc26ba"),
                            Category = 2,
                            Description = "La notebook lenovo IDEAPAD 1 es exactamente lo que necesita una computadora portátil de uso diario. Vea programas en una pantalla HD de hasta 14 pulgadas con un marco extremadamente delgado.",
                            Discount = 39,
                            ImageUrl = "https://i.imgur.com/aC6Tpbp.jpg",
                            Name = "Notebook Lenovo Ideapad 1",
                            Price = 599.999m
                        },
                        new
                        {
                            ProductId = new Guid("312cc244-12f8-451e-820b-a64630ef43cb"),
                            Category = 2,
                            Description = "Descubrí la excepcional ligereza y delgadez de este portátil, convirtiéndolo en un equipo versátil y fácil de llevar a todas partes. Su pantalla Full HD de 15.6 pulgadas no solo proporciona comodidad para trabajar, sino que también garantiza una calidad de imagen excepcional.",
                            Discount = 0,
                            ImageUrl = "https://i.imgur.com/zfmWA1i.jpg",
                            Name = "Notebook HP 15 Core i3 8GB",
                            Price = 879.999m
                        },
                        new
                        {
                            ProductId = new Guid("278af4c4-742c-4e96-9804-767629459eab"),
                            Category = 3,
                            Description = "Detalles: Acetato, Polarizado, Calibre 49, Filtro UV 100%.",
                            Discount = 10,
                            ImageUrl = "https://i.imgur.com/Vj9Dy6c.jpg",
                            Name = "Anteojos Vulk Rolling Stones I Can T",
                            Price = 172.299m
                        },
                        new
                        {
                            ProductId = new Guid("f2e6eb9b-6d45-48b8-92db-361ae9c2dcd7"),
                            Category = 3,
                            Description = " Detalles: Plastico, Polarizado, Filtro UV 100%.",
                            Discount = 0,
                            ImageUrl = "https://i.imgur.com/j9QGnA4.jpg",
                            Name = "Anteojos Vulk Evan C14 Hombre",
                            Price = 27.199m
                        },
                        new
                        {
                            ProductId = new Guid("759c833c-0221-411f-b198-5a8bee6aee30"),
                            Category = 3,
                            Description = "Billetera de la marca Billabong, confeccionada con Cuero sintético, con monedero y porta tarjetas interior.",
                            Discount = 0,
                            ImageUrl = "https://i.imgur.com/xontgIp.jpeg",
                            Name = "Billetera Billabong Dimension M Wllt Hombre",
                            Price = 29.999m
                        },
                        new
                        {
                            ProductId = new Guid("25307730-5fe2-4676-8efc-92d6dff30efd"),
                            Category = 3,
                            Description = ":Una riñonera con estilo universitario, hecha parcialmente con materiales reciclados Más que una marca de nuestro legado, el monograma del Trifolio de esta canguro adidas es una declaración sutil que hace que cada outfit sea más prémium.",
                            Discount = 10,
                            ImageUrl = "https://i.imgur.com/GNccHqp.jpeg",
                            Name = "Riñonera adidas Wb L Trefoil Aop",
                            Price = 58.999m
                        },
                        new
                        {
                            ProductId = new Guid("417fe660-911b-4449-be55-ea7ab82eda3b"),
                            Category = 4,
                            Description = "Con indicadores de confort, incluso pequeños cambios de temperatura, control de humedad en un vistazo. Supervisión continua de los cambios de temperatura y humedad en el interior. Atención y apoyo durante todo el año para la salud de su familia",
                            Discount = 50,
                            ImageUrl = "https://i.imgur.com/X6ZHONh.jpg",
                            Name = "Reloj monitor de temperatura y humedad Xiaomi",
                            Price = 126.789m
                        },
                        new
                        {
                            ProductId = new Guid("e58f9896-7c35-4bd1-8af3-b4207e5c9080"),
                            Category = 4,
                            Description = "Estructura: 80% madera maciza y 20% aglomerado de partículas.Asiento: Cinchas elásticas y placa poliéster soft. Relleno: Guata y copo de poliéster. Costura: Costura reforzada. Patas: Inyección plástica.",
                            Discount = 39,
                            ImageUrl = "https://i.imgur.com/JrI2KwS.jpg",
                            Name = "Sillón Esquinero Gris Piazza Chaise Longue G3",
                            Price = 985m
                        },
                        new
                        {
                            ProductId = new Guid("0f8006dc-44bd-4e41-976f-db90f7af5861"),
                            Category = 4,
                            Description = "Botón táctil » Luz: 3000 K - 6000 K » 120 LED por metro (1360 lúmenes) » Función antiempañe » Función lupa (x5) » Reloj, fecha, temperatura » Alimentación 220 V » Transformador 12 V",
                            Discount = 0,
                            ImageUrl = "https://i.imgur.com/xontgIp.jpg",
                            Name = "Espejos Grandes Redondo Pared Con Luz Led Moderno Tactil",
                            Price = 383.613m
                        },
                        new
                        {
                            ProductId = new Guid("f699c2a3-4119-4ba5-8166-e6e6cf86fe02"),
                            Category = 4,
                            Description = "Diseño pensado a detalle para que desbloquees el siguiente nivel de confort en tu lugar reservado para jugar hasta que en la pantalla de tu adversario aparezca game over.",
                            Discount = 0,
                            ImageUrl = "https://i.imgur.com/bHhg5Jk.jpg",
                            Name = "Escritorio Gamer PC 2M",
                            Price = 217.14m
                        },
                        new
                        {
                            ProductId = new Guid("2b21831b-d545-4d80-b0d2-2a4f739e4cb4"),
                            Category = 5,
                            Description = "Remueve impurezas de la piel, efecto antiarrugas y antiojeras, reduce las arrugas de ojos y ojeras, promueve la absorción de la crema para la piel, alivia la fatiga de los ojos, 2 velocidades de vibración, funciona con pila CR2032 (incluida).",
                            Discount = 35,
                            ImageUrl = "https://i.imgur.com/Zo8NGy8.jpg",
                            Name = "Balanza De Vidrio Para Baño Beurer Gs-10 ",
                            Price = 31.04m
                        },
                        new
                        {
                            ProductId = new Guid("855fed98-c34a-48f5-838e-f3ff723ea645"),
                            Category = 5,
                            Description = " Estructura: 80% madera maciza y 20% aglomerado de partículas.Asiento: Cinchas elásticas y placa poliéster soft. Relleno: Guata y copo de poliéster. Costura: Costura reforzada. Patas: Inyección plástica.",
                            Discount = 51,
                            ImageUrl = "https://i.imgur.com/6m2ZjKx.jpeg",
                            Name = "Masajeador Facial Anti Arrugas y Ojeras",
                            Price = 29.999m
                        },
                        new
                        {
                            ProductId = new Guid("a6cf2675-4a42-4e7b-bf3e-7898004eafb3"),
                            Category = 5,
                            Description = "adnic presenta su nueva linea de Mascara Led ! Esta mascara es ideal para el cuidado de la piel y combatir el acné. Gracias a su gran pantalla táctil hace que sea muy fácil a la hora de usar. Cuenta con 192 luces LED y 7 diferentes colores. Dependiendo del tipo de luz elegida se pueden realizar diferentes tratamientos.",
                            Discount = 0,
                            ImageUrl = "https://i.imgur.com/bSnTN9d.jpeg",
                            Name = "Mascara Facial Led Gadnic LT3.0 Terapia Acné Rejuvenecimiento",
                            Price = 77.999m
                        },
                        new
                        {
                            ProductId = new Guid("ebd13ef0-7fb2-4368-b038-5ddbef6628a9"),
                            Category = 5,
                            Description = "Es una crema de una avanzada tecnología que no es grasosa y brinda una mayor potencia de humectación para pieles o zonas con mayor resequedad o sensibles",
                            Discount = 20,
                            ImageUrl = "https://i.imgur.com/1dbYScK.jpeg",
                            Name = "Crema Hidratante Piel Extra Seca Y Sensible Cetaphil ",
                            Price = 29.19m
                        },
                        new
                        {
                            ProductId = new Guid("04ed858a-c681-4ae4-ab53-999b0acbd419"),
                            Category = 6,
                            Description = "Este casco puede usarse tanto en jóvenes como adultos ya que es regulable de los 57CM a los 62CM. Es muy fácil de trasladar ya que es muy liviano y cómodo a la hora de usar y hacer viajes largos.",
                            Discount = 23,
                            ImageUrl = "https://i.imgur.com/OvyMriJ.jpeg",
                            Name = "Casco Bicicleta Zykel Con Visera",
                            Price = 27.624m
                        },
                        new
                        {
                            ProductId = new Guid("78047171-d43b-443b-9628-e0a144eb5c74"),
                            Category = 6,
                            Description = "Este casco puede usarse para adultos, es talle L con un calce cómodo y regulable.",
                            Discount = 0,
                            ImageUrl = "https://i.imgur.com/Df9qwaf.jpeg",
                            Name = "Casco Bicicleta Raleigh 29vent.",
                            Price = 48.889m
                        },
                        new
                        {
                            ProductId = new Guid("b0584d95-bb62-4044-b0f7-aad319606dff"),
                            Category = 6,
                            Description = "Cinta motorizada para caminar y correr. Su consola LED posee un diseño moderno con luz blanca y 4 ventanas que permiten monitorear velocidad, tiempo, distancia y calorías consumidas.",
                            Discount = 25,
                            ImageUrl = "https://i.imgur.com/wxiH52I.jpeg",
                            Name = "Cinta Motorizada Randers ARG-472 ",
                            Price = 999.999m
                        },
                        new
                        {
                            ProductId = new Guid("0b78972c-e3c8-4df2-a7a8-147325139e74"),
                            Category = 6,
                            Description = "Una bicicleta fija, equipada con un volante de inercia resistente, puede proporcionar Más potencia y te ofrece una experiencia deportiva desafiante",
                            Discount = 0,
                            ImageUrl = "https://i.imgur.com/orXy11W.jpeg",
                            Name = "Bicicleta Fija Para Spinning Tm Acero",
                            Price = 272.599m
                        },
                        new
                        {
                            ProductId = new Guid("6cade72d-d993-44da-890b-c93982361d96"),
                            Category = 7,
                            Description = "Panel LED con teclas luminosas, colorida pantalla, entrada y salida de audio, control deslizante de volumen, efectos scratch, pulsadores para varios efectos, selección de ritmo, altavoz, auriculares.",
                            Discount = 29,
                            ImageUrl = "https://i.imgur.com/kkMdvBA.jpeg",
                            Name = "Consola Dj Mixer Juguete con Luz y Sonido  ",
                            Price = 56.999m
                        },
                        new
                        {
                            ProductId = new Guid("c717ec6b-7889-4193-a952-e81e236935a0"),
                            Category = 7,
                            Description = "Incluye 70 piezas, 2 muñecos, 15 stickers, guía de armado, edad recomendada 5 años, juguete no tóxico, fabricado sin ftalatos ni colorantes.",
                            Discount = 0,
                            ImageUrl = "https://i.imgur.com/nCDdUY9.jpeg",
                            Name = "Juego De Bloques Blocky Policías",
                            Price = 8.999m
                        },
                        new
                        {
                            ProductId = new Guid("4f4883fc-eebd-4f9c-8b12-3957b24418ab"),
                            Category = 7,
                            Description = "Incluye 70 piezas, 2 muñecos, 15 stickers, guía de armado, edad recomendada 5 años, juguete no tóxico, fabricado sin ftalatos ni colorantes.",
                            Discount = 22,
                            ImageUrl = "https://i.imgur.com/jLo3URK.jpeg",
                            Name = "Juego De Bloques Blocky Bomberos",
                            Price = 8.999m
                        },
                        new
                        {
                            ProductId = new Guid("0d810fa1-f6e5-4c07-9682-8b0a74defc73"),
                            Category = 7,
                            Description = "Monopoly Classic es un juego de mesa divertido y emocionante que es perfecto para familias y amigos. Es un juego de estrategia, negociación y suerte, y siempre hay algo nuevo que aprender.",
                            Discount = 29,
                            ImageUrl = "https://i.imgur.com/Ov0H3lN.jpeg",
                            Name = "Juego de Mesa Monopoly Clásico",
                            Price = 99.99m
                        },
                        new
                        {
                            ProductId = new Guid("53c26ac4-6906-45e2-9847-2d4dfd38f910"),
                            Category = 8,
                            Description = "Nada supera el sabor de una Coca-Cola. Diseñado para acompañar cada momento, el sabor de la Coca-Cola es un clásico que perdura desde hace más de 130 años. Deliciosa y refrescante.",
                            Discount = 0,
                            ImageUrl = "https://i.imgur.com/P3Ca0DP.jpeg",
                            Name = "Gaseosa Coca-cola Sabor Original 2.25 L",
                            Price = 2.175m
                        },
                        new
                        {
                            ProductId = new Guid("4c23c2a7-2eff-4e75-accd-b026d46425fd"),
                            Category = 8,
                            Description = "Agua carbonatada, azúcar, colorante, aromas (contiene cafeína), acidulante y edulcorantes. No contiene alérgenos de obligada declaración. Mejor que bueno.",
                            Discount = 0,
                            ImageUrl = "https://i.imgur.com/BljOtPT.jpeg",
                            Name = "Gaseosa Pepsi Botella 2lt",
                            Price = 2.4m
                        },
                        new
                        {
                            ProductId = new Guid("866dc5bf-efda-4dcb-935c-f2de39837115"),
                            Category = 8,
                            Description = "Paquete en versión de 500g, Porotos alubias, puede contener soja",
                            Discount = 0,
                            ImageUrl = "https://i.imgur.com/jSEf9QO.jpeg",
                            Name = "Porotos Mister Food Alubia",
                            Price = 550m
                        },
                        new
                        {
                            ProductId = new Guid("06e8d3fe-d0e2-4667-b7b3-0c2a733e1d08"),
                            Category = 8,
                            Description = "Quínoa, zanahoria deshidratada, cebolla deshidratada, morrón deshidratado, espinaca deshidratada, perejil deshidratado, sal, azúcar, pimentón dulce, nuez moscada, coriandro, pimienta blanca.",
                            Discount = 0,
                            ImageUrl = "https://i.imgur.com/TpkqwZ0.jpeg",
                            Name = "Quinoa Con Vegetales Y Champignones",
                            Price = 5.85m
                        },
                        new
                        {
                            ProductId = new Guid("a6c33233-2e59-4a7c-9ec7-2188e1e942e1"),
                            Category = 9,
                            Description = "Editorial: Oberon, páginas: 336, idioma Español. Clasificación Ingenieria, Tecnica Y Ciencias Exactas - Otras Ciencias Exactas - Astronomia",
                            Discount = 0,
                            ImageUrl = "https://i.imgur.com/kZgLnD3.jpeg",
                            Name = "Vida En Marte - David A. Weintraub",
                            Price = 23.56m
                        },
                        new
                        {
                            ProductId = new Guid("03b32429-219f-4521-8350-2fe4916a74ac"),
                            Category = 9,
                            Description = "Editorial: RBA Bolsillo, páginas: 160, idioma Español. Clasificación Ingenieria, Tecnica Y Ciencias Exactas - Ingenieria - General",
                            Discount = 0,
                            ImageUrl = "https://i.imgur.com/25XVmpI.jpeg",
                            Name = "Inteligencia Artificial (bolsillo) - Ignasi Belda Reig",
                            Price = 15.9m
                        },
                        new
                        {
                            ProductId = new Guid("275928b0-89f1-4549-9243-9d645ff4a2ed"),
                            Category = 9,
                            Description = "Que son las contraseñas? ?Como se construyen? ?En que momento de la historia surgieron? Estas son solo algunas de las preguntas que sirven como disparador para que Martin Paul Eve despliegue su conocimiento sobre las implicancias y el funcionamiento de las contraseñas",
                            Discount = 0,
                            ImageUrl = "https://i.imgur.com/Hz41tOe.jpeg",
                            Name = "Una Historia De Las Contr45eñ4s - Martin Paul Eve ",
                            Price = 17.999m
                        },
                        new
                        {
                            ProductId = new Guid("3dfd2a91-a604-4f96-9d59-3ee71147ecc2"),
                            Category = 9,
                            Description = "Explora la evolución de los videojuegos desde sus orígenes en el MIT hasta su posición actual como fenómeno mundial. Analiza la influencia de los arcades en la popularización del medio, el legado de Mario y su impacto en la cultura pop, y el éxito de Pokémon como estrategia de mercadeo basada en la nostalgia.",
                            Discount = 0,
                            ImageUrl = "https://i.imgur.com/6Z2OS3v.jpeg",
                            Name = "FENOMENOS GAMERS, de Nicolas Rabago",
                            Price = 19.6m
                        },
                        new
                        {
                            ProductId = new Guid("7c944be6-b026-4996-a0a4-3ab5940ae5fc"),
                            Category = 10,
                            Description = "La cortadora de cesped eléctrica DAC1600 de Daewoo cuenta con una potencia de 1600 watts , mientras que, el voltaje es de 220/50 Hz. A su vez posee una manija ergonómica para una mayor comodidad del usuario, es plegable y pertenece a la línea ECO. ",
                            Discount = 42,
                            ImageUrl = "https://i.imgur.com/mqeEhE0.jpeg",
                            Name = "Cortadora de césped Daewoo Eléctrica ",
                            Price = 349.999m
                        },
                        new
                        {
                            ProductId = new Guid("f7f70071-3f41-4f15-ac71-04d0e8766515"),
                            Category = 10,
                            Description = " La bordeadora de césped severbon cuenta con motor eléctrico y una potencia de 1000 watts. Posee una manija ajustable en altura, que te brindará una mayor comodidad y te facilitará su uso.",
                            Discount = 40,
                            ImageUrl = "https://i.imgur.com/QeJly67.jpeg",
                            Name = "Bordeadora Eléctrica Severbon",
                            Price = 99.999m
                        },
                        new
                        {
                            ProductId = new Guid("0a08f1c6-5fce-4e41-a7e9-c33bcb46ee68"),
                            Category = 10,
                            Description = "Con su potencia de 105 bar podés dejar reluciente cualquier material o superficie. Su impacto de agua a alta presión es entre diez y cincuenta veces más potente que las mangueras de jardín, lo que hace más eficaz y fácil el proceso de limpieza.",
                            Discount = 33,
                            ImageUrl = "https://i.imgur.com/L2rsHLN.jpeg",
                            Name = "Hidrolavadora Daewoo 1200 Watts 105 Bar con Autostop",
                            Price = 149.999m
                        },
                        new
                        {
                            ProductId = new Guid("03373629-8ca2-4af1-9401-63cc43c0f397"),
                            Category = 10,
                            Description = "Con la Motosierra Philco podés hacer cortes profesionales de todo tipo de maderas, para podar, cortar árboles y hacer numerosos trabajos de jardinería. Es tu aliada perfecta para superar cualquier obstáculo. Con su diseño ergonómico y potente motor, te brinda la confianza y el control necesarios para realizar trabajos eficientes y precisos",
                            Discount = 0,
                            ImageUrl = "https://i.imgur.com/kuXUj62.jpeg",
                            Name = "Motosierra Philco A Nafta Espada 45 Cm 52cc ",
                            Price = 199.999m
                        });
                });

            modelBuilder.Entity("Domain.Entities.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPay")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SaleId");

                    b.ToTable("Sale", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SaleProduct", b =>
                {
                    b.Property<int>("ShoppingCartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoppingCartId"));

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("Product")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Sale")
                        .HasColumnType("int");

                    b.HasKey("ShoppingCartId");

                    b.HasIndex("Product");

                    b.HasIndex("Sale");

                    b.ToTable("SaleProduct", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.HasOne("Domain.Entities.Caregory", "Categoria")
                        .WithMany("Products")
                        .HasForeignKey("Category")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Domain.Entities.SaleProduct", b =>
                {
                    b.HasOne("Domain.Entities.Product", "Producto")
                        .WithMany("SaleProducts")
                        .HasForeignKey("Product")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Sale", "Venta")
                        .WithMany("SaleProducts")
                        .HasForeignKey("Sale")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Domain.Entities.Caregory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Navigation("SaleProducts");
                });

            modelBuilder.Entity("Domain.Entities.Sale", b =>
                {
                    b.Navigation("SaleProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
